spin_manifest_version = 2

[application]
name = "website"
version = "0.1.0"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "website"

[component.website]
source = "target/wasm32-wasi/release/website.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
dependencies_inherit_configuration = true
[component.website.dependencies]
"example:qr/qr" = { path = "../qr-generator-cached/target/wasm32-unknown-unknown/release/qr_generator_cached.wasm" }
[component.website.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
